# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 17 Oct 2009 16:39:13 +0000
*               @ALL        0  
allusers:*      @users      1
*               @teachers   1
*               @schulportfolio       16

