#!/bin/bash

# this script builds tar packages based on the 
# linuxmuster-portfolio debian package for various
# scenarios to run without PaedML Linux
# GPL 2
# Frank Schiebel <schiebel@aeg-reutlingen.de>


TARFILE=$1
SUBSUBVERSION=$2
SCRIPTDIR=`dirname $0`







