#!/bin/sh -e

DATADIR="/home/linuxmuster-portfolio/data/"
EXAMPLES="/var/lib/linuxmuster-portfolio/data/"
HELP="/var/lib/linuxmuster-portfolio/help/"


# Only install examples on fresh install
if [ ! -f $DATADIR/DELETEME_FOR_FRESH_EXAMPLES ]; then
   echo "Copying example data..."
   cp -r $EXAMPLES/*  $DATADIR/
   echo "   done."

   echo "Copying help pages..."
   cp -r $HELP/*  $DATADIR/
   echo "   done."
fi

# Permissions of data dir: must be writable for www-data
if [ -d /home/linuxmuster-portfolio/data ]; then
    chown -R www-data: /home/linuxmuster-portfolio/data 
fi
if [ -d /usr/share/linuxmuster-portfolio/lib/plugins ]; then
    chown -R www-data: /usr/share/linuxmuster-portfolio/lib/plugins 
fi
if [ -d /etc/linuxmuster-portfolio/ ]; then
    chown -R root:www-data /etc/linuxmuster-portfolio/
    chmod -R g+w /etc/linuxmuster-portfolio/
fi
if [ -f /usr/share/linuxmuster/config/dist.conf ]; then  
     . /usr/share/linuxmuster/config/dist.conf
fi

basedn=`grep basedn $NETWORKSETTINGS | sed "s/^.*\"\(.*\)\".*$/\1/"`

sed -i'' -e"s/\(ou=accounts,\).*;/\1 $basedn\';/" /etc/linuxmuster-portfolio/local.php
sed -i'' -e"s/\(ou=groups,\).*;/\1 $basedn\';/" /etc/linuxmuster-portfolio/local.php

if [ -x /etc/init.d/apache2 ]; then
/etc/init.d/apache2 reload
fi

