#!/bin/sh -e

DATADIR="/home/linuxmuster-portfolio/data/"
EXAMPLES="/var/lib/linuxmuster-portfolio/data/"
HELP="/var/lib/linuxmuster-portfolio/help/"
TEMPLATE="/usr/share/linuxmuster-portfolio/lib/tpl/portfolio"


# Only install examples on fresh install
if [ ! -f $DATADIR/pages/start.txt ]; then
   echo "Copying example data..."
   cp -r $EXAMPLES/*  $DATADIR/
   echo "   done."

   echo "Copying help pages..."
   cp -r $HELP/*  $DATADIR/
   echo "   done."
fi

if [ ! -d $DATADIR/media/wiki/logo/ ]; then
     echo "Creating logo directory..."
     mkdir -p $DATADIR/media/wiki/logo/
     touch $DATADIR/media/wiki/logo/dummy_dont_delete.png
     echo "   done."
fi

LOGOACL=0
grep -q "wiki:logo:" /etc/linuxmuster-portfolio/acl.auth.php && LOGOACL=1
if [ $LOGOACL -eq 0 ]; then
  echo "wiki:logo:*     @ALL    1" >> /etc/linuxmuster-portfolio/acl.auth.php
fi

# link to local plugins
for PLUGIN in /etc/linuxmuster-portfolio/plugins/*; do 
PLUGINNAME=`echo $PLUGIN | awk -F/ '{print $5}'`
  if [ -d $PLUGIN ]; then
    echo "Found local plugin $PLUGIN"
    cd /usr/share/linuxmuster-portfolio/lib/plugins 
    if [ ! -h ./${PLUGINNAME} ]; then 
       ln -s $PLUGIN
    fi
  fi
done

# check for media_attic and media_meta upon upgrading
if [ ! -d /home/linuxmuster-portfolio/data/media_attic ]; then
    mkdir -p /home/linuxmuster-portfolio/data/media_attic
fi
if [ ! -d /home/linuxmuster-portfolio/data/media_meta ]; then
    mkdir -p /home/linuxmuster-portfolio/data/media_meta
fi


# Permissions of data dir: must be writable for www-data
if [ -d /home/linuxmuster-portfolio/data ]; then
    chown -R www-data: /home/linuxmuster-portfolio/data 
fi
if [ -d /usr/share/linuxmuster-portfolio/lib/plugins ]; then
    chown -R www-data: /usr/share/linuxmuster-portfolio/lib/plugins 
fi
if [ -d /etc/linuxmuster-portfolio/ ]; then
    chown -R root:www-data /etc/linuxmuster-portfolio/
    chmod -R g+w /etc/linuxmuster-portfolio/
fi
if [ -f /usr/share/linuxmuster/config/dist.conf ]; then  
     . /usr/share/linuxmuster/config/dist.conf
fi


basedn=`grep basedn $NETWORKSETTINGS | sed "s/^.*\"\(.*\)\".*$/\1/"`


if [ -f /etc/linuxmuster-portfolio/local.php ]; then
    sed -i'' -e"s/\(ou=accounts,\).*;/\1 $basedn\';/" /etc/linuxmuster-portfolio/local.php
    sed -i'' -e"s/\(ou=groups,\).*;/\1 $basedn\';/" /etc/linuxmuster-portfolio/local.php
    sed -i "s/\(\$conf\['template'\].*=\).*/\1 'portfolio2';/" /etc/linuxmuster-portfolio/local.php
fi


if [ -x /etc/init.d/apache2 ]; then
/etc/init.d/apache2 reload
fi

