#!/bin/sh -e

# Permissions of data dir: must be writable for www-data
if [ -d /home/linuxmuster-portfolio/data ]; then
    chown -R www-data: /home/linuxmuster-portfolio/data 
fi

if [ -f /usr/share/linuxmuster/config/dist.conf ]; then  
     . /usr/share/linuxmuster/config/dist.conf
fi

basedn=`grep basedn $NETWORKSETTINGS | sed "s/^.*\"\(.*\)\".*$/\1/"`

sed -i'' -e"s/\(ou=accounts,\).*;/\1 $basedn\';/" /etc/linuxmuster-portfolio/local.php
