#!/bin/sh -e

DATADIR="/home/linuxmuster-portfolio/data/"
EXAMPLES="/var/lib/linuxmuster-portfolio/data/"
HELP="/var/lib/linuxmuster-portfolio/help/"
TEMPLATE="/usr/share/linuxmuster-portfolio/lib/tpl/portfolio"


# Are we updating from ACH Template?
echo "Executing preints..."
VECTORUPDATE=0
grep -q "Based on 'ACH' Template for DokuWiki" ${TEMPLATE}/main.php && VECTORUPDATE=1

if [ $VECTORUPDATE -eq 1 ]; then
    echo "Updating from ACH -> vector..."
    rm -f /etc/linuxmuster-portfolio/user.css
    rm -f /etc/linuxmuster-portfolio/*.dist
    if [ -f /etc/linuxmuster-portfolio/images/header_logo.png ]; then 
       cp /etc/linuxmuster-portfolio/images/header_logo.png /etc/linuxmuster-portfolio/logo.png.backup 
    fi
    rm -rf /etc/linuxmuster-portfolio/images/
    if [ -d /etc/linuxmuster-portfolio/usermod ]; then 
        rm -rf /etc/linuxmuster-portfolio/usermod
    fi
    if [ -d /etc/linuxmuster-portfolio/openschulportfolio ]; then 
        rm -rf /etc/linuxmuster-portfolio/openschulportfolio
    fi
fi

