#!/bin/sh -e

DATADIR="/home/linuxmuster-portfolio/data/"
EXAMPLES="/var/lib/linuxmuster-portfolio/data/"
HELP="/var/lib/linuxmuster-portfolio/help/"
TEMPLATE="/usr/share/linuxmuster-portfolio/lib/tpl/portfolio"


# Are we updating from ACH Template?
echo "Executing preints..."
VECTORUPDATE=0
grep -q "Based on 'ACH' Template for DokuWiki" ${TEMPLATE}/main.php && VECTORUPDATE=1

if [ $VECTORUPDATE -eq 1 ]; then
    echo "Updating from ACH -> vector..."
    rm -f /etc/linuxmuster-portfolio/user.css
    rm -f /etc/linuxmuster-portfolio/*.dist
fi

