#!/bin/bash

#
# This script provides the ability to reinstall
# prdefined pages and/or help pages in the 
# linuxmsuter-portfolio wiki
#
# @author Frank Schiebel <frank@linuxmuster.net>
#
# GPLv2
#


