<?php
// This file is automatically generated
$bt_settings['type'] = 'exec';
$bt_settings['pages'] = 'checked';
$bt_settings['revisions'] = '';
$bt_settings['subscriptions'] = '';
$bt_settings['media'] = 'checked';
$bt_settings['config'] = '';
$bt_settings['templates'] = '';
$bt_settings['plugins'] = '';
